"use client";

import Link from "next/link";
import { useMemo, useState, type ReactNode } from "react";

type Screen = "home" | "events" | "attendance" | "lineup" | "approved" | "ice" | "arena" | "services" | "skates" | "camps" | "profile";
type Status = "Придёт" | "Не ответил" | "Не придёт";
type Player = { name: string; number: number; role: string; status: Status };

const players: Player[] = [
  { name: "Сергей Иванов", number: 17, role: "Нападающий", status: "Придёт" },
  { name: "Алексей Петров", number: 10, role: "Нападающий", status: "Придёт" },
  { name: "Дмитрий Сидоров", number: 91, role: "Нападающий", status: "Придёт" },
  { name: "Андрей Кузнецов", number: 27, role: "Защитник", status: "Придёт" },
  { name: "Илья Морозов", number: 44, role: "Защитник", status: "Придёт" },
  { name: "Артём Волков", number: 33, role: "Вратарь", status: "Придёт" },
  { name: "Максим Егоров", number: 1, role: "Вратарь", status: "Не ответил" },
  { name: "Павел Орлов", number: 74, role: "Нападающий", status: "Придёт" },
  { name: "Никита Фёдоров", number: 21, role: "Нападающий", status: "Не придёт" },
  { name: "Роман Васильев", number: 52, role: "Защитник", status: "Не ответил" },
];

const titles: Record<Screen, string> = {
  home: "Главная", events: "События", attendance: "Явка", lineup: "Состав", approved: "Готово",
  ice: "Поиск льда", arena: "Бронирование", services: "Мои услуги", skates: "Подкатки", camps: "Сборы", profile: "Профиль",
};

function Card({ children, className = "" }: { children: ReactNode; className?: string }) {
  return <section className={`rounded-3xl bg-[#2d332f] p-5 ${className}`}>{children}</section>;
}
function Head({ over, title, right }: { over?: string; title: string; right?: ReactNode }) {
  return <div className="flex items-end justify-between gap-3"><div>{over && <p className="text-[10px] font-black uppercase tracking-[.16em] text-[#20d1a8]">{over}</p>}<h2 className="mt-1 text-xl font-black">{title}</h2></div>{right}</div>;
}
function Pill({ children, active = false }: { children: ReactNode; active?: boolean }) {
  return <span className={active ? "rounded-xl bg-[#20d1a8]/15 px-3 py-2 text-[10px] font-black text-[#20d1a8]" : "rounded-xl bg-white/5 px-3 py-2 text-[10px] font-black text-white/40"}>{children}</span>;
}
function PlayerRow({ player }: { player: Player }) {
  const cls = player.status === "Придёт" ? "text-[#20d1a8]" : player.status === "Не придёт" ? "text-red-200" : "text-amber-200";
  return <div className="flex items-center gap-3 rounded-2xl bg-[#121715] p-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white/10 text-sm font-black">{player.number}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{player.name}</b><small className="text-white/35">{player.role}</small></span><span className={`text-[10px] font-black ${cls}`}>{player.status}</span></div>;
}

function BottomNav({ screen, go }: { screen: Screen; go: (s: Screen) => void }) {
  const data: Array<[Screen, string, string]> = [["home", "⌂", "Главная"], ["events", "▦", "События"], ["lineup", "◎", "Состав"], ["ice", "❄", "Лёд"], ["profile", "◉", "Профиль"]];
  return <nav className="fixed bottom-4 left-1/2 z-50 grid w-[calc(100%-24px)] max-w-md -translate-x-1/2 grid-cols-5 gap-1 rounded-[26px] border border-white/10 bg-[#2d332f]/95 p-2 shadow-2xl backdrop-blur">{data.map(([id, icon, label]) => { const selected = screen === id || (id === "events" && screen === "attendance") || (id === "lineup" && screen === "approved") || (id === "ice" && screen === "arena") || (id === "profile" && ["services", "skates", "camps"].includes(screen)); return <button key={id} onClick={() => go(id)} className={selected ? "rounded-2xl bg-[#20d1a8] py-2 text-[#121715]" : "rounded-2xl py-2 text-white/45"}><span className="block text-lg font-black">{icon}</span><span className="block text-[9px] font-black">{label}</span></button>; })}</nav>;
}

function Home({ go }: { go: (s: Screen) => void }) {
  return <div className="space-y-5">
    <Card><div className="flex items-center gap-4"><div className="flex h-20 w-20 items-center justify-center rounded-3xl bg-[#20d1a8] text-3xl font-black text-[#121715]">А</div><div><p className="text-sm font-bold text-white/40">Главный тренер</p><h2 className="mt-1 text-2xl font-black">Александр Иванов</h2><p className="mt-2 text-xs font-black text-[#20d1a8]">ХК «Айсберг»⌄</p></div></div></Card>
    <Card><Head over="Ближайшее событие" title="Игра · 26 июля, 21:30" /><div className="mt-4 rounded-3xl bg-[#121715] p-4"><b className="text-lg">Айсберг — Северные Волки</b><p className="mt-1 text-sm text-white/40">«Юбилейный» · сбор в 20:45</p><div className="mt-4 grid grid-cols-3 gap-2 text-center">{[["13", "Придут", "text-[#20d1a8]"], ["4", "Не придут", "text-red-200"], ["6", "Нет ответа", "text-amber-200"]].map(([n,l,c]) => <div key={l} className="rounded-2xl bg-[#2d332f] p-3"><p className={`text-2xl font-black ${c}`}>{n}</p><p className="text-[9px] text-white/35">{l}</p></div>)}</div><button onClick={() => go("attendance")} className="mt-4 h-14 w-full rounded-[28px] bg-[#20d1a8] font-black text-[#121715]">Открыть событие</button></div></Card>
    <Card><Head title="Требует внимания" /><div className="mt-4 space-y-2">{[["6 игроков не ответили", "attendance"], ["Нет запасного вратаря", "attendance"], ["Состав не опубликован", "lineup"]].map(([t,s]) => <button key={t} onClick={() => go(s as Screen)} className="flex w-full items-center justify-between rounded-2xl bg-[#121715] p-4 text-left text-sm font-black"><span>{t}</span><span className="text-[#20d1a8]">→</span></button>)}</div></Card>
    <div className="grid grid-cols-2 gap-3"><button onClick={() => go("ice")} className="rounded-3xl bg-[#2d332f] p-5 text-left"><span className="text-2xl">❄</span><b className="mt-4 block">Найти лёд</b><small className="text-white/35">Свободные окна арен</small></button><button onClick={() => go("skates")} className="rounded-3xl bg-[#2d332f] p-5 text-left"><span className="text-2xl">↗</span><b className="mt-4 block">Подкатки</b><small className="text-white/35">Заявки и участники</small></button></div>
  </div>;
}

function Events({ go }: { go: (s: Screen) => void }) {
  const days = [21,22,23,24,25,26,27,28,29,30,31,1,2,3];
  return <div className="space-y-5"><Card><Head title="Июль 2026" right={<Pill>ХК «Айсберг»</Pill>} /><div className="mt-5 grid grid-cols-7 gap-1 text-center">{["Пн","Вт","Ср","Чт","Пт","Сб","Вс"].map(x => <small key={x} className="font-black text-white/30">{x}</small>)}{days.map(d => <button key={d} onClick={() => d===26 && go("attendance")} className={d===26 ? "mt-2 min-h-14 rounded-2xl bg-[#20d1a8] font-black text-[#121715]" : "mt-2 min-h-14 rounded-2xl bg-[#121715] font-black"}>{d}{[24,26,29].includes(d) && <i className="mx-auto mt-1 block h-1.5 w-1.5 rounded-full bg-[#ff0a8a]" />}</button>)}</div></Card><Card><Head over="Пятница, 26 июля" title="События команды" /><button onClick={() => go("attendance")} className="mt-4 w-full rounded-3xl bg-[#121715] p-4 text-left"><div className="flex justify-between"><span><small className="font-black text-[#20d1a8]">ИГРА</small><b className="mt-1 block text-lg">Айсберг — Северные Волки</b><small className="text-white/40">Стадион «Юбилейный»</small></span><Pill active>21:30</Pill></div><div className="mt-4 flex gap-2"><Pill active>13 придут</Pill><Pill>6 без ответа</Pill></div></button><div className="mt-3 rounded-3xl bg-[#121715] p-4"><small className="font-black text-[#ff0a8a]">ТРЕНИРОВКА</small><b className="mt-1 block text-lg">Командная тренировка</b><small className="text-white/40">24 июля · 19:00</small></div></Card></div>;
}

function Attendance({ go }: { go: (s: Screen) => void }) {
  const [filter, setFilter] = useState<"Все" | Status>("Все");
  const visible = useMemo(() => players.filter(p => filter === "Все" || p.status === filter), [filter]);
  return <div className="space-y-5"><Card><small className="font-black text-[#20d1a8]">ИГРА · 26 ИЮЛЯ, 21:30</small><h2 className="mt-2 text-2xl font-black">Айсберг — Северные Волки</h2><p className="mt-2 text-sm text-white/40">Стадион «Юбилейный» · сбор в 20:45</p></Card><Card><div className="flex gap-2 overflow-x-auto">{(["Все","Придёт","Не ответил","Не придёт"] as const).map(x => <button key={x} onClick={() => setFilter(x)} className={filter===x ? "shrink-0 rounded-2xl bg-[#20d1a8] px-4 py-3 text-xs font-black text-[#121715]" : "shrink-0 rounded-2xl bg-[#121715] px-4 py-3 text-xs font-black text-white/50"}>{x}</button>)}</div><div className="mt-4 space-y-2">{visible.map(p => <PlayerRow key={p.name} player={p} />)}</div></Card><button className="h-14 w-full rounded-[28px] bg-amber-400 font-black text-[#121715]">Напомнить не ответившим</button><button onClick={() => go("lineup")} className="h-14 w-full rounded-[28px] bg-[#20d1a8] font-black text-[#121715]">Составить состав</button></div>;
}

function Lineup({ go }: { go: (s: Screen) => void }) {
  const [colors, setColors] = useState(["#ef4444", "#3b82f6", "#f8fafc"]);
  const [picker, setPicker] = useState<number | null>(null);
  const palette = ["#ef4444", "#3b82f6", "#f8fafc", "#facc15", "#22c55e"];
  return <div className="space-y-5"><Card><Head over="Игра · черновик" title="Айсберг — Северные Волки" right={<Pill>13 + 1 ВР</Pill>} /></Card>{colors.map((color, line) => <Card key={line} className="overflow-hidden !p-0"><div className="h-2" style={{backgroundColor:color}} /><div className="p-5"><div className="flex items-center justify-between"><span><b>{line+1}-е звено</b><small className="block text-white/35">Выберите цвет маек</small></span><span className="flex gap-1">{palette.map(c => <button key={c} onClick={() => setColors(x => x.map((v,i)=>i===line?c:v))} className="h-7 w-7 rounded-full border-2 border-[#121715]" style={{backgroundColor:c}} />)}</span></div><div className="mt-4 grid grid-cols-5 gap-2">{Array.from({length:5},(_,i) => { const p = line===0 ? players[i] : line===1 ? players[(i+7)%players.length] : undefined; return <button key={i} onClick={() => !p && setPicker(line)} className="min-h-24 rounded-2xl bg-[#121715] p-2">{p ? <><span className="mx-auto flex h-10 w-10 items-center justify-center rounded-full bg-white/10 text-xs font-black">{p.number}</span><small className="mt-2 block truncate font-black">{p.name.split(" ")[0]}</small><small className="text-white/35">{i<3?"НП":"ЗЩ"}</small></> : <><span className="text-xl text-white/30">+</span><small className="mt-2 block text-white/30">Игрок</small></>}</button>;})}</div></div></Card>)}<Card><Head title="Вратари" /><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[#121715] p-4"><small className="font-black text-[#20d1a8]">ОСНОВНОЙ</small><b className="mt-2 block">Артём Волков · №33</b></div><div className="rounded-2xl border border-dashed border-white/15 bg-[#121715] p-4 text-white/35">Запасной не выбран</div></div></Card><button className="h-14 w-full rounded-[28px] bg-[#2d332f] font-black">Сохранить черновик</button><button onClick={() => go("approved")} className="h-14 w-full rounded-[28px] bg-[#20d1a8] font-black text-[#121715]">Утвердить состав</button>{picker !== null && <div className="fixed inset-0 z-[80] flex items-end justify-center bg-black/70 p-3"><Card className="max-h-[70vh] w-full max-w-md overflow-y-auto"><Head title={`Игрок в ${picker+1}-е звено`} right={<button onClick={()=>setPicker(null)} className="h-10 w-10 rounded-full bg-[#121715]">×</button>} /><div className="mt-4 space-y-2">{players.filter(p=>p.status==="Придёт").map(p=><button key={p.name} onClick={()=>setPicker(null)} className="w-full text-left"><PlayerRow player={p}/></button>)}</div></Card></div>}</div>;
}

function Approved({ go }: { go: (s: Screen) => void }) {
  return <div className="space-y-5"><Card className="py-8 text-center"><div className="mx-auto flex h-24 w-24 items-center justify-center rounded-full bg-[#20d1a8]/15 text-5xl text-[#20d1a8]">✓</div><h2 className="mt-6 text-3xl font-black">Состав утверждён</h2><p className="mt-3 text-sm leading-6 text-white/45">Игрокам отправлены звено, позиция, цвет маек и время сбора.</p></Card><Card><Head title="Что дальше" /><div className="mt-4 space-y-2"><button onClick={()=>go("lineup")} className="flex w-full justify-between rounded-2xl bg-[#121715] p-4 font-black"><span>Изменить состав</span><span>→</span></button><button className="flex w-full justify-between rounded-2xl bg-[#121715] p-4 font-black"><span>Написать команде</span><span>→</span></button><button onClick={()=>go("home")} className="flex w-full justify-between rounded-2xl bg-[#121715] p-4 font-black"><span>На главную</span><span>→</span></button></div></Card></div>;
}

function Ice({ go }: { go: (s: Screen) => void }) {
  return <div className="space-y-5"><Card><Head over="Санкт-Петербург" title="Свободный лёд" /><div className="mt-4 space-y-2">{[["ДАТА","27 июля"],["ВРЕМЯ","19:00–23:30"],["РАЙОН","Любой район"]].map(([a,b])=><button key={a} className="flex h-14 w-full items-center justify-between rounded-2xl bg-[#121715] px-4 text-left"><span><small className="block font-black text-white/30">{a}</small><b>{b}</b></span><span>›</span></button>)}</div><button className="mt-4 h-14 w-full rounded-[28px] bg-[#20d1a8] font-black text-[#121715]">Найти лёд</button></Card>{[["Ледовый дворец «Озерки»","5,2 км","16 000 ₽"],["Стадион «Юбилейный»","7,8 км","18 000 ₽"]].map(([name,dist,price])=><button key={name} onClick={()=>go("arena")} className="w-full rounded-3xl bg-[#2d332f] p-5 text-left"><div className="h-32 rounded-3xl bg-[linear-gradient(135deg,#1d594a,#121715_70%)]"/><div className="mt-4 flex justify-between gap-3"><span><b className="block text-lg">{name}</b><small className="text-white/40">{dist} · раздевалка · душ</small></span><Pill active>{price}</Pill></div><div className="mt-4 rounded-2xl bg-[#121715] p-3 font-black">27 июля · 20:30–22:00 →</div></button>)}</div>;
}

function Arena({ go }: { go: (s: Screen) => void }) {
  const [time,setTime]=useState("20:30–22:00"), [booked,setBooked]=useState(false);
  if(booked) return <div className="space-y-5"><Card className="py-8 text-center"><div className="mx-auto flex h-24 w-24 items-center justify-center rounded-full bg-[#20d1a8]/15 text-5xl text-[#20d1a8]">✓</div><h2 className="mt-6 text-3xl font-black">Лёд забронирован</h2><p className="mt-3 text-white/45">27 июля · {time}<br/>Ледовый дворец «Озерки»</p></Card><button onClick={()=>go("events")} className="h-14 w-full rounded-[28px] bg-[#20d1a8] font-black text-[#121715]">Добавить событие команде</button></div>;
  return <div className="space-y-5"><Card><div className="h-40 rounded-3xl bg-[linear-gradient(135deg,#1d594a,#121715_70%)]"/><h2 className="mt-4 text-2xl font-black">Ледовый дворец «Озерки»</h2><p className="mt-2 text-sm text-white/40">Крытый лёд · раздевалка · душ · парковка</p></Card><Card><Head over="27 июля" title="Свободное время" /><div className="mt-4 space-y-2">{["19:00–20:30","20:30–22:00","22:00–23:30"].map((x,i)=><button key={x} onClick={()=>setTime(x)} className={time===x?"flex w-full justify-between rounded-2xl border border-[#20d1a8] bg-[#20d1a8]/10 p-4 font-black":"flex w-full justify-between rounded-2xl bg-[#121715] p-4 font-black"}><span>{x}</span><span className="text-[#20d1a8]">{i?"18 000 ₽":"16 000 ₽"}</span></button>)}</div></Card><button onClick={()=>setBooked(true)} className="h-14 w-full rounded-[28px] bg-[#20d1a8] font-black text-[#121715]">Забронировать · 18 000 ₽</button></div>;
}

function Catalog({ kind, go }: { kind: "services"|"skates"|"camps"; go: (s:Screen)=>void }) {
  const [created,setCreated]=useState(false);
  const data = kind==="services" ? [["Индивидуальная тренировка","1 500 ₽ / 60 мин","Активна"],["Подкатка: техника катания","2 000 ₽ / человек","Активна"],["Тренировка для защитников","1 800 ₽ / 60 мин","Черновик"]] : kind==="skates" ? [["Подкатка выходного дня","27 июля · 14/18 участников","Собрано"],["Вечерняя подкатка","30 июля · 10/16 участников","Набор"],["Для защитников","2 августа · 8/12 участников","Набор"]] : [["Летние сборы 2026","10–20 августа · Сочи","24/30"],["Подготовка к сезону","1–7 сентября · Екатеринбург","18/25"],["Новогодние сборы","2–8 января · Казань","Черновик"]];
  return <div className="space-y-5"><Card><Head over={kind==="services"?"Публичный профиль":"Организация занятий"} title={titles[kind]} right={<button onClick={()=>setCreated(true)} className="rounded-2xl bg-[#20d1a8] px-3 py-2 text-xs font-black text-[#121715]">+ Создать</button>} /></Card>{created&&<Card className="border border-[#20d1a8]/30 bg-[#20d1a8]/10"><b className="text-[#20d1a8]">Черновик создан</b><p className="mt-2 text-sm text-white/50">Заполните описание, дату, стоимость и условия.</p></Card>}{data.map(([a,b,c])=><Card key={a}><div className="flex justify-between gap-3"><span><b className="block text-lg">{a}</b><small className="mt-1 block text-white/40">{b}</small></span><Pill active={c!=="Черновик"}>{c}</Pill></div><div className="mt-4 h-2 rounded-full bg-white/10"><div className="h-2 w-2/3 rounded-full bg-[#20d1a8]"/></div></Card>)}{kind==="services"&&<button onClick={()=>go("skates")} className="h-14 w-full rounded-[28px] bg-[#20d1a8] font-black text-[#121715]">Перейти к подкаткам</button>}{kind==="skates"&&<button onClick={()=>go("camps")} className="h-14 w-full rounded-[28px] bg-[#2d332f] font-black">Хоккейные сборы →</button>}</div>;
}

function Profile({ go }: { go:(s:Screen)=>void }) {
  return <div className="space-y-5"><Card><div className="flex items-center gap-4"><div className="flex h-20 w-20 items-center justify-center rounded-3xl bg-[#20d1a8] text-3xl font-black text-[#121715]">А</div><div><p className="text-sm text-white/40">Главный тренер</p><h2 className="mt-1 text-2xl font-black">Александр Иванов</h2><p className="mt-1 text-xs text-[#20d1a8]">Публичный профиль активен</p></div></div></Card><Card><Head title="Рабочие инструменты" /><div className="mt-4 space-y-2">{[["services","₽","Мои услуги","3 услуги"],["skates","↗","Подкатки","3 занятия"],["camps","▤","Хоккейные сборы","2 набора"]].map(([s,i,t,d])=><button key={s} onClick={()=>go(s as Screen)} className="flex w-full items-center gap-3 rounded-2xl bg-[#121715] p-4 text-left"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-white/5 text-xl">{i}</span><span className="flex-1"><b className="block">{t}</b><small className="text-white/35">{d}</small></span><span>→</span></button>)}</div></Card><Card><Head title="Данные тренера" /><div className="mt-4 space-y-2">{[["СПЕЦИАЛИЗАЦИЯ","Главный тренер"],["СТАЖ","12 лет"],["РЕЙТИНГ","4,9 · 38 отзывов"]].map(([a,b])=><div key={a} className="rounded-2xl bg-[#121715] p-4"><small className="font-black text-[#20d1a8]">{a}</small><b className="mt-1 block">{b}</b></div>)}</div></Card><Link href="/coach/profile" className="flex h-14 items-center justify-center rounded-[28px] bg-[#20d1a8] font-black text-[#121715]">Открыть действующий профиль</Link></div>;
}

export default function CoachDemoPage() {
  const [screen,setScreen]=useState<Screen>("home"), [history,setHistory]=useState<Screen[]>([]);
  const go=(next:Screen)=>{ if(next===screen)return; setHistory(h=>[...h,screen].slice(-15)); setScreen(next); window.scrollTo({top:0,behavior:"smooth"}); };
  const back=()=>setHistory(h=>{const x=[...h], p=x.pop()||"home"; setScreen(p); return x;});
  return <main className="min-h-screen bg-[#121715] px-5 pb-32 pt-8 text-white"><div className="mx-auto max-w-md"><header className="flex items-center justify-between gap-3"><div className="flex min-w-0 items-center gap-3">{screen!=="home"&&<button onClick={back} className="h-11 w-11 shrink-0 rounded-2xl bg-[#2d332f] text-xl">←</button>}<div><p className="text-xs text-white/35">ХМ 5.1 · Тренер · живой макет</p><h1 className="text-3xl font-black">{titles[screen]}</h1></div></div><Link href="/coach" className="shrink-0 rounded-2xl bg-[#2d332f] px-3 py-3 text-[10px] font-black text-white/50">В приложение</Link></header><div className="mt-5 rounded-2xl border border-[#20d1a8]/25 bg-[#20d1a8]/10 p-3 text-xs font-bold text-white/60">Тестовые данные. Серверные операции не выполняются.</div><div className="mt-5">{screen==="home"&&<Home go={go}/>} {screen==="events"&&<Events go={go}/>} {screen==="attendance"&&<Attendance go={go}/>} {screen==="lineup"&&<Lineup go={go}/>} {screen==="approved"&&<Approved go={go}/>} {screen==="ice"&&<Ice go={go}/>} {screen==="arena"&&<Arena go={go}/>} {screen==="services"&&<Catalog kind="services" go={go}/>} {screen==="skates"&&<Catalog kind="skates" go={go}/>} {screen==="camps"&&<Catalog kind="camps" go={go}/>} {screen==="profile"&&<Profile go={go}/>}</div></div><BottomNav screen={screen} go={go}/></main>;
}
